oesProgrammingTest/Models/BiggestEmotion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace oesProgrammingTest.Models
{
    public class BiggestEmotion
    {
        public string Emotion { get; set; }
        public float Confidence { get; set; }
    }
}

oesProgrammingTest/Models/ClassMate.cs
using Microsoft.ProjectOxford.Common.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace oesProgrammingTest.Models
{
    public class ClassMate
    {
        Dictionary<string, float> emotions = new Dictionary<string, float>();
        public ClassMate(string fileName, EmotionScores emotionScores)
        {
            FileName = fileName;
            EmotionScores = emotionScores;
            SetEmotionList(emotionScores);
        }

        private void SetEmotionList(EmotionScores emotionScores)
        {
            emotions.Add("Happy", emotionScores.Happiness);
            emotions.Add("Anger", emotionScores.Anger);
            emotions.Add("Contempt", emotionScores.Contempt);
            emotions.Add("Disgust", emotionScores.Disgust);
            emotions.Add("Fear", emotionScores.Fear);
            emotions.Add("Neutral", emotionScores.Neutral);
            emotions.Add("Sadness", emotionScores.Sadness);
            emotions.Add("Surprise", emotionScores.Surprise);
        }

        public string FileName { get; set; }
        public EmotionScores EmotionScores { get; set; }
        public BiggestEmotion GetBiggestEmotion()
        {
            var item = emotions
                        .OrderByDescending(x => x.Value)
                        .FirstOrDefault();
            return new BiggestEmotion()
            {
                Emotion = item.Key,
                Confidence = item.Value
            };

        }
        public override string ToString()
        {
            return $"{FileName} - {emotions.OrderByDescending(x => x.Value).FirstOrDefault().Key}";
        }
    }
}

oesProgrammingTest/Controllers/EmotionAnalyzerController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.ProjectOxford.Emotion.Contract;
using Microsoft.ProjectOxford.Emotion;
using oesProgrammingTest.Models;
using System.Configuration;

namespace oesProgrammingTest.Controllers
{
    public class EmotionAnalyzerController : Controller
    {
        DirectoryInfo _dirInfo;
        public EmotionAnalyzerController()
        {
            _dirInfo = new DirectoryInfo(GetUploadDirectory());
        }
        public ActionResult Index()
        {
            @ViewBag.UploadFiles = GetUploadedFiles();
            return View();
        }
        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {

            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    SaveUploadedFile(file);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = $"ERROR Uploading File: {ex.Message.ToString()}";
                }
            }
            else
                ViewBag.Message = "No file specified.";

            return View();
        }
        private List<string> GetUploadedFiles()
        {
            return _dirInfo
                        .GetFiles()
                        .OrderByDescending(x => x.CreationTime)
                        .Select(x => x.Name)
                        .ToList() ?? new List<string>();
        }
        public async Task<ActionResult> Analyze()
        {
            var currentFile = Request.QueryString["fileName"];
            
            if (string.IsNullOrEmpty(currentFile))
                RedirectToAction("Index");

            string fileAndLocation = Path.Combine(GetUploadDirectory(), currentFile);
            var emotionClient = new EmotionServiceClient(ConfigurationManager.AppSettings["EmotionApiKey"]);

            var emotionResults = await emotionClient.RecognizeAsync(System.IO.File.Open(fileAndLocation,FileMode.Open));

            Image img = Image.FromStream(System.IO.File.Open(fileAndLocation, FileMode.Open));

            List<ClassMate> classMates = new List<ClassMate>();
            foreach (var item in emotionResults)
                classMates.Add(ProcessItem(img, item));

            @ViewBag.CurrentFile = currentFile;
            @ViewBag.ClassMates = classMates;
            return View();
        }
        private void SaveUploadedFile(HttpPostedFileBase file)
        {
            string path = Path.Combine(GetUploadDirectory(),
                                       Path.GetFileName(file.FileName));
            file.SaveAs(path);
        }
        private string GetUploadDirectory()
        {
            return Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~"),
                                "Uploads");
        }
        private void ClearAnalyzeFolder()
        {
            var dir = new DirectoryInfo(GetAnalyzeDirectory());

            foreach (var file in dir.EnumerateFiles("*.jpg"))
                file.Delete();
        }
        private string GetAnalyzeDirectory()
        {
            return Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~"),
                                "AnalyzeDirectory");
        }
        private ClassMate ProcessItem(Image img, Emotion emotion)
        {
            var point = new Point(emotion.FaceRectangle.Left, emotion.FaceRectangle.Top);
            var size = new Size(emotion.FaceRectangle.Width, emotion.FaceRectangle.Height);
            var rec = new Rectangle(point, size);
            var croppedFace = cropImage(img, rec);
            var myUniqueFileName = string.Format(@"{0}.jpg", DateTime.Now.Ticks);
            croppedFace.Save(Path.Combine(GetAnalyzeDirectory(), myUniqueFileName),
                System.Drawing.Imaging.ImageFormat.Jpeg);

            return new ClassMate(myUniqueFileName, emotion.Scores);
        }
        private Image cropImage(Image img, Rectangle cropArea)
        {
            Bitmap bmpImage = new Bitmap(img);
            return bmpImage.Clone(cropArea, bmpImage.PixelFormat);
        }
    }
}

oesProgrammingTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.ProjectOxford.Emotion.Contract;
using Microsoft.ProjectOxford.Emotion;
using oesProgrammingTest.Models;
using System.Configuration;

namespace oesProgrammingTest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        private string GetUploadDirectoryPath()
        {
            return Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~"),
                                "Uploads");
        }
        
    }
}

oesProgrammingTest/Views/EmotionAnalyzer/Analyze.cshtml
@{
    ViewBag.Title = "Emotion Analyze";
}

<img src="~/Uploads/@ViewBag.CurrentFile" height="400" width="400" class="img-thumbnail">

<div class="container">
    @foreach (var classMate in ViewBag.ClassMates)
    {
        <div class="row">
            <div class="col-md-2">
                <img src="~/AnalyzeDirectory/@classMate.FileName" height="200" width="200" class="img-thumbnail">
            </div>
            <div class="col-md-2">
                @classMate.GetBiggestEmotion().Emotion
            </div>
        </div>
    }
</div>

oesProgrammingTest/Views/EmotionAnalyzer/Index.cshtml
@{
    ViewBag.Title = "Emotion Index";
}

Emotion Index
<br />
<div class="container">
    <div class="row">
        @foreach (var uploadedFile in ViewBag.UploadFiles)
            {
            <div class="col">
                <a href="EmotionAnalyzer/Analyze?fileName=@uploadedFile">
                    <img src="Uploads/@uploadedFile" height="400" width="400" class="img-thumbnail">
                </a>
            </div>
        }
    </div>
</div>

@Html.ActionLink("Upload", "Upload", "EmotionAnalyzer")<br />
@Html.ActionLink("Analyze", "Analyze", "EmotionAnalyzer")<br />

oesProgrammingTest/Views/EmotionAnalyzer/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}
Pick your character
<img src="~/images/Inside-Out-Characters.jpg" />

@using (Html.BeginForm("Upload", "EmotionAnalyzer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label for="file">Upload a file to process:</label>
    <input type="file" class="btn btn-default" name="file" id="file" /><br><br>
    <input type="submit" class="btn btn-sm btn-default" value="Upload File" />
}

oesProgrammingTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Hello :)</h1>
    <p class="lead">Some stuff here.</p>
</div>

oesProgrammingTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - OES Programming Test</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("OES Programming", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li><a href="https://docs.google.com/presentation/d/1nWGdQU15J6m3FM8BzKv89lnZ2HRiyU30HjwWR9n0V6s/edit?usp=sharing">Presentation</a></li>
                    <li><a href="http://www.haplessgenius.com/mocha/" target="_blank">CoCo</a></li>
                    <li><a href="http://spritebox.com/flash.html" target="_blank">Sprite Box</a></li>
                    <li>@Html.ActionLink("Inside Out", "Index", "EmotionAnalyzer")</li>
                    <!--
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Inside Out<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Upload", "Upload", "EmotionAnalyzer")</li>
                            <li>@Html.ActionLink("Analyze", "Analyze", "EmotionAnalyzer")</li>
                        </ul>
                    </li>
                        -->
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - OES Programming Test</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>